MD007:
  indent: 4

MD013: false

MD040:
  allowed_languages: [
    'html', 'css', 'js', 'ts', 'vue', 'react', 'jsx', 'json',
    'py', 'java', 'c', 'cpp',
    'bat', 'ps1', 'sh',         # 这些表示的是文件
    'shell', 'text', 'syntax', 'draw' ] # shell 表示的是命令行，比如 cmd, powershell, git bash, linux 终端中运行的命令
  language_only: true # 为 true 时，将不允许在语言后添加信息，比如 js start-line=2
